version: '3.8'

networks:
  API:
    driver: bridge

volumes:
  static:
  media:
  postgres_data:

services:

  api:
    build: app/.
    container_name: api
    restart: unless-stopped
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
    networks:
      - API
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: unless-stopped
    networks:
      - API
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    networks:
      - API
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static:/opt/app/static
      - media:/opt/app/media
    environment:
      NGINX_SET_REAL_IP_FROM: 192.168.1.0/24
    depends_on:
      - api
    ports:
      - ${NGINX_PORT}:80
